SELECT SCH.SCHEDULE_DAY_AHEAD,
SUM(CASE when SCH.LDC_DUNS = 'JAPAN0003' then 1 else 0 end) AS TEPCO_QTY_SUM,
SUM(CASE when SCH.LDC_DUNS = 'JAPAN0004' then 1 else 0 end) AS CHUBU_QTY_SUM,
SUM(CASE when SCH.LDC_DUNS = 'JAPAN0006' then 1 else 0 end) AS KANSAI_QTY_SUM,
SUM(CASE when SCH.LDC_DUNS = 'JAPAN0009' then 1 else 0 end) AS KYUSHU_QTY_SUM
FROM SCHEDULES SCH
WHERE SCH.GROUP_ID = '102'
AND SCH.SCHEDULE_DATE between '20170803' and '20170805'
AND SCH.REPLACED IS NULL
GROUP BY SCH.SCHEDULE_DAY_AHEAD;
