UPDATE IDRKH idr   
SET IDR.PURP_CODE = '99'
WHERE IDR.PURP_CODE = '00'  
AND IDR.EVENT_ID IN    
(SELECT EVT.EVENT_ID           
FROM SS_EVENT_LOG evt, IDRKH idr, SS_GROUP_EVENTS GE        
WHERE EVT.EVENT_ID = IDR.EVENT_ID
AND EVT.EVENT_ID = GE.EVENT_ID
AND GE.GROUP_ID = '78'
AND GE.EVENT_ID = IDR.EVENT_ID
AND EVT.CLIENT_DUNS = '171841633' 
AND EVT.TP_DUNS = '183529049'
AND EVT.EVENT_DESC = 'USID' 
AND EVT.EVENT_TIMESTAMP BETWEEN '21-OCT-2016' AND '27-OCT-2016')