select distinct AP.LDC_ACCOUNT_NUM, 
    MAX(UA.ESP_ACCT_NUMB) AS "ESP_ACCT_NUMB", 
    CO.CUSTOMER_NAME AS "FULL_NAME", 
   UPPER (substr(CO.CUSTOMER_NAME,1,4)) AS "TRUNCATED_NAME", 
    AP.DISTRIBUTOR_NAME
FROM CW_DISCOUNTENERGY.ACCOUNT_PACKAGE AP, 
     CW_DISCOUNTENERGY.CUSTOMER CO, 
     CW_DISCOUNTENERGY.MARKET_TRANSACTION_QUEUE_ARC MTQ, 
     ESG_TRX2.USG_ACCOUNT UA
WHERE AP.CUSTOMER_TKN = CO.CUSTOMER_TKN
    AND MTQ.TRANS_ID = UA.SEND_TRX_ID 
        AND AP.LDC_ACCOUNT_NUM = UA.LDC_ACCT_NUMB
            AND AP.LDC_ACCOUNT_NUM IN ('317100378010')
            group by AP.LDC_ACCOUNT_NUM, CO.CUSTOMER_NAME, AP.DISTRIBUTOR_NAME
ORDER BY AP.DISTRIBUTOR_NAME;
